export const FETCH_PRODUCTS_BY_CATEGORY_ID = 'products/BY_CATEGORY_ID';
export const RECEIVE_PRODUCTS_BY_CATEGORY_ID_SUCCESS = 'products/RECEIVE_SUCCESS';
export const RECEIVE_PRODUCTS_BY_CATEGORY_ID_FAILURE = 'products/RECEIVE_FAILURE';
export const FETCH_PRODUCTS_BY_CATEGORY_ID_ERROR = 'products/FETCH_ERROR';
